name: CI

on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - master
      - "v*"
    # always run CI for tags
    tags:
      - "*"

jobs:
  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm lint

  tests:
    needs: lint
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm test

  try-scenarios:
    name: Tests - ${{ matrix.ember-try-scenario }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    needs: ember-tests

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          # - ember-lts-3.4
          # - ember-lts-3.8
          # - ember-lts-3.12
          # - ember-lts-3.16
          # - ember-lts-3.20
          # - ember-lts-3.24
          - ember-lts-3.28
          # - ember-lts-4.4
          # - ember-lts-4.8
          - ember-lts-4.12
          # - ember-lts-5.4
          # - ember-lts-5.8
          - ember-lts-5.12
          - ember-release
          - ember-beta
        allow-failure: [false]
        include:
          - ember-try-scenario: ember-canary
            allow-failure: true
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
        working-directory: test-app
